### ISSUE TITLE
[Maintaince] Current situation and community help

### ISSUE THREAD

**Issue by divine** [mongodb/laravel-mongodb#2499]
Hello,

The current situation with this library is that it will be abandoned soon and yes, it's real.

I don't have the ability to fix the underlying issues (neither does anyone else) as I'm in no way in control of the repository. I can't merge and release the new version due to a permission problem.

It has been 3 years that @jenssegers is silent. Honestly without @Smolevich, @Giacomo92, and other contributors that recovered this library last time, it would be dead already a few years back.

I've invested my personal time and tried my best to keep it alive but this silence isn't acceptable to move this library forward.

@jenssegers if you're not interested in taking care of just transfer to an organization that the community could take care of it. Last time you explained that you don't have time due to new work and went silent completely for a few years...

We as a community tried to communicate but no replies were received.

Sorry for a little bit of the aggressive tone but I'm tired of spending my personal time while somebody who could help solve all of this problem doesn't even reply.

Personal repositories aren't meant to be managed by a few collaborators so moving forward is to transfer this repository to an organization that could handle it.  @alcaeus @jmikola maybe you can help with the transfer of this to the MongoDB organization or community-driven organization would be a better fit?

I probably could do some workaround to release the new version but I won't do that as I can't even merge my https://github.com/jenssegers/laravel-mongodb/pull/2471 which is sad indeed.

Let me know what you think.

Thanks!

**Comment by jenssegers** [comment]
What would be your recommendation? What organisation would be a good fit to keep this library alive?

**Comment by alcaeus** [comment]
Hi everyone,

MongoDB has a strong interest in having well-maintained framework integrations, which is why [we're currently hiring for a Senior PHP Engineer](https://www.mongodb.com/careers/jobs/4751309) to help us maintain and improve the integrations to Laravel and Symfony. We are open to moving this library to the MongoDB organisation, but that would need the approval of @jenssegers, the current maintainers, and our product department (@techbelle). At the same time, we wouldn't want to take over the library and just lock out current maintainers, so that's something I would want to discuss as well.

An alternative would be to move this library to either the Laravel umbrella (which would require discussing things with @taylorotwell), the [FriendsOfPHP](https://github.com/friendsofphp) organisation, or a newly created organisation with the sole purpose of housing this repository, along with a minimal owner structure capable of making decisions beneficial to the future of the library. We are open to all of these options, and it mainly depends on @jenssegers and the current maintainers to help us choose one. To that end, we should probably get together and discuss a way forward. I would recommend a virtual meeting given that maintainers are usually geographically separated. I will also be attending LaraconEU next week (January 26th and 27th), so in case any of the maintainers, contributors, or users of this library are attending as well please don't hesitate to come to our booth and talk to me about this library.

@jenssegers, @divine: if you'd like to discuss things in a more private setting first, please contact me. I don't want to make it too easy for spambots, but the email address I use in my commits receives email so that would be one way to get in touch with me.

**Comment by divine** [comment]
> What would be your recommendation? What organisation would be a good fit to keep this library alive?
> 
> I'm really thankful for all the work you guys have been doing with the library. I've been quite out of the PHP ecosystem for the past years and I don't want to be a blocking factor in moving forward with the library.

Thank you for getting back. I've tried contacting the owners of a few PHP organizations but they refuse with the suggestion of having a separate organization for this library solely.

> if you'd like to discuss things in a more private setting first, please contact me.

@alcaeus I've sent you an email.

Thanks!

**Comment by iglazunoff** [comment]
Hi everyone!

In my opinion, this library requires total refactoring, since it does not meet the methodologies and approaches that are used when working with MongoDB. Moreover, the team and I had to write our own solution and abandon this library in order to get a friendly codestyle when using Laravel, we also had to write a query builder for aggregation pipelines from scratch, which is not in this library at all.

@alcaeus 
It would be interesting for me to work on a library for Laravel, since I have been using PHP + MongoDB for more than 4 years on large and small projects and I live the dream of making an ideal library for PHP and integration with PHP frameworks for this database.

If my impulse is interesting to you, I suggest we talk)

gmail: iglazunoff39@gmail.com
telegram: @iglazunoff

**Comment by alcaeus** [comment]
After some internal discussions, we are indeed interested in taking over maintenance of this library. @jenssegers if you are interested in MongoDB taking over maintenance of this library, please reach out to me so we can discuss details. You can find me on Twitter (https://twitter.com/alcaeus), or you can grab the email address from one of my recent commits and contact me there.

**Comment by divine** [comment]
We had a conversation with @alcaeus and the best for this repository would be MongoDB as an organization to take it over so they can move this library forward. This way it'll be handled properly and the library users will be happy.

@jenssegers please kindly answer @alcaeus.

Thanks!

**Comment by divine** [comment]
@jenssegers Hello, we're stuck without any reply.

Could you please kindly transfer this repository to the community repository, which was created by me, `laramongo` after which it will be moved to the "MongoDB" organization so they can take care of this library?

I'm with @Smolevich; he and me will still be the maintainers, but under the MongoDB organization, it will be handled properly so it won't be dead after a few years.

The reason for a temporal movement is that it's not possible to do this without communication from your side, so I'll take care of it.

I hope you'll see my message and accept the transfer.

Thanks!

**Comment by Wernke96** [comment]
@divine could lararmongo organization just fork this repo?

**Comment by Wernke96** [comment]
So what happens to this repo?

**Comment by alcaeus** [comment]
We are currently putting the pieces in place to migrate the repository so that there won't be any disruptions in service. We'll post an update once there are news.

**Comment by zane-shus** [comment]
> We are currently putting the pieces in place to migrate the repository so that there won't be any disruptions in service. We'll post an update once there are news.

I am just starting a new project, does this mean it will be easy to use the current repo and easily convert when its moved?  (I am new to Laravel and Mongo)

**Comment by alcaeus** [comment]
Yes.

**Comment by Wernke96** [comment]
> We are currently putting the pieces in place to migrate the repository so that there won't be any disruptions in service. We'll post an update once there are news.

Very exciting to see this project get the love that it needs. Thank you for the response I look forward to hearing more news on this.

**Comment by alcaeus** [comment]
> Any update on release with Laravel 10 support?

It is done when it's done. If you want to test it early, please use the `dev-master` version and let us know if it works or if you encounter any issues.

**Comment by subhamchb** [comment]
> Any update on release with Laravel 10 support?

I have created an PR to support Laravel 10.

**Comment by subhamchbty** [comment]
> Any update on release with Laravel 10 support?

I have created a PR for Laravel 10 support.

**Comment by puuble** [comment]
> > Any update on release with Laravel 10 support?
> 
> It is done when it's done. If you want to test it early, please use the `dev-master` version and let us know if it works or if you encounter any issues.

it is works as well for now. I tried it.

**Comment by alcaeus** [comment]
> It has been a couple of months now since this update. Is there any news that can be shared?

We're still putting pieces into place. It's taking longer than I had hoped, but we're still committed.

> I have a new project about to start, and would love to know where things currently stand before I integrate this library into it.

There is no other alternative at this time, so I would suggest you integrate this library. As per my previous comment, my wish is for us to take over maintenance of this library without any disruption.

**Comment by john-ilesanmi** [comment]
Please which version/PR branch is most stable for laravel 10?

**Comment by john-ilesanmi** [comment]
Thanks @haridarshan21.  I used `dev-master`

**Comment by Winfle** [comment]
Thank you, guys, for the input!

**Comment by lbrutti** [comment]
Hello guys, thanks for the great work you're doing in keeping this library alive.
As in #1974 , the future of EmbedsOne/Many/OneOrMany seems uncertain, but in my company we are using them in several parts of our projects.
Since they are still present in current 3.9 version, what should I expect?

Thanks!

**Comment by alcaeus** [comment]
@lbrutti Embedded documents are a core concept of MongoDB, and as such we are not planning to remove them entirely.

However, I did previously discuss this with @divine, and there are some issues around the current implementation of embedded documents and how people use them. We will address this at some point, but rest assured that the library will continue to support embedded documents.

**Comment by ithuis** [comment]
@alcaeus Now that you guys are adopting this package, is there anything on your roadmap for providing a mongodb integration for laravel scout?

**Comment by jmikola** [comment]
@ithuis: There are no immediate plans as there is presently a lot to do just for this package itself, but I've opened [PHPORM-28](https://jira.mongodb.org/browse/PHPORM-28) so we can track your request down the line.

**Comment by ithuis** [comment]
ok, i understand. Then i will give it a try myself.
also, i dont have permission to see the request, but i trust you completely ;-)

**Comment by mshamaseen** [comment]
@alcaeus would be great if you could provide more news about when this library could be maintained again. The Laravel community is so eager for this package to be maintained again as it is the most used Laravel-Mongodb package and the one that thousands of projects depend on!

We appreciate MongoDB team's time and effort on this.

**Comment by divine** [comment]
> @alcaeus would be great if you could provide more news about when this library could be maintained again. The Laravel community is so eager for this package to be maintained again as it is the most used Laravel-Mongodb package and the one that thousands of projects depend on!
> 
> We appreciate MongoDB team's time and effort on this.

I've tried my best to push this forward but there is a delay that sadly went out of its way.

**Comment by alcaeus** [comment]
Hello everyone! I wanted to provide an update to the current situation. It took a lot longer than we anticipated, but I can now confirm that MongoDB will be maintaining this library going forward. Over the next few days, we will be transferring this repository to the MongoDB organisation on GitHub (https://github.com/mongodb), making sure that everything continues to work as expected.

We have been hard at work over the past weeks making improvements so that we can ship a 4.0 release with compatibility for Laravel 10. There are a few things left to do, but we will provide an update once we have a release date in mind. Please be aware that the upcoming release will also result in a new package name on packagist. Upgrade instructions will be provided to ensure a smooth transition from 3.9 to 4.0.
