### ISSUE TITLE
Match date not working on aggregation

### ISSUE THREAD

**Issue by joao-ufjf** [mongodb/laravel-mongodb#2508]
Hello, I am trying to reproduce an aggregation I built on Compass.

Basically, I have an Item model and want to filter the results based on date, then group and sort by it.

![image](https://user-images.githubusercontent.com/5231378/218189693-69a82f20-40da-4e14-991d-93d5571a3592.png)

And the results do NOT match the date, showing record from before the start of month.
It always get me the same result with `'$gte' => ['$received_at', Carbon::now()->startOfMonth()]` or `'$gte' => ['$received_at', '2023-02-01']`.

What is working as expected is when I use Eloquent like `MongoItem::whereDate('received_at', '>=', Carbon::now()->startOfMOnth())->get();`.

An example of MongoItem

`
{
  "_id": "63e55322de392",
  "quantity": 1,
  "received_at": "2023-01-16T13:10:10.464533-03:00",
  ...
}
`

Appreciate the help.

**Comment by alcaeus** [comment]
When you send something to the database using `raw`, no preparation will be done on the query. This means that you need to query data the way it is saved in the database, not the way it is represented in your model. For simple types this doesn't make a difference, but dates are stored as `UTCDateTime` instances, not `Carbon` dates. Since the `Carbon` class extends `DateTime`, you can pass it as [constructor argument to `UTCDateTime`](https://www.php.net/manual/en/mongodb-bson-utcdatetime.construct.php):
```
$utcDateTime = new \MongoDB\BSON\UTCDateTime(Carbon::now()->startOfMonth());
```

Looking at your pipeline above, I'll also suggest to confirm that you're indeed storing a date string in the `received_at` field - if you've added this field to the `$dates` property in your model it will already be stored as a date. `$toDate` will handle this case gracefully, but it would still save the query engine from running a `$project` stage that isn't necessary.

**Comment by iqionly** [comment]
I also experienced the same thing, and luckily found a solution here
