### ISSUE TITLE
Count performance decreased drastically after upgrading to 4.x

### ISSUE THREAD

**Issue by BBrey** [mongodb/laravel-mongodb#2626]
- Laravel-mongodb Version: 4.x
- PHP Version: 8.1
- Database Driver & Version: 4.4

### Description:
When upgrading laravel to version 10 we had to upgrade to 4.0.rc2 (dev-master on jenssegers?)
This is causing the ->count() to be very slow without a where.

### Steps to reproduce
1. Test a count with 3.9.5 with 500k+ records in a collection 
2. Test a count with 4.x with 500k+ records in a collection

### Expected behaviour
The speed should be the same as 3.9.5

### Actual behaviour
We now have timeouts when getting the count.

**Comment by GromNaN** [comment]
This is expected. The change was done in https://github.com/mongodb/laravel-mongodb/commit/4514964145c70c37e6221be8823f8f73a201c259.
 MongoDB's [`Collection::count()` is deprecated](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-count/) because it wasn't clear enough to users that the result was an estimate using the database metadata.

We choose to change the implementation to use [`Collection::countDocuments()`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-countDocuments/) because this method provides accurate results. Using [`Collection::estimatedDocumentCount`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-estimatedDocumentCount/) would have preserved the previous behavior.
We had to choose one of both implementations for the Laravel implementation, but I would agree that each method has its own use cases.

You can get the more performant estimation using raw query:

```php
Model::raw(fn ($collection) => $collection->estimatedDocumentCount())
```

Would it help if we added a new method `Model::estimatedCount()`?

**Comment by BBrey** [comment]
@GromNaN yeah but we need the where of course! if the estimate is the estimate of the collection it's useless for us.

**Comment by jmikola** [comment]
> we need the where of course! if the estimate is the estimate of the collection it's useless for us.
Or did the previous version give a wrong count?

This is discussed in more detail in the [Count API Details](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#count-api-details) with the MongoDB drivers' CRUD spec. The summarize, the [`count` command](https://www.mongodb.com/docs/manual/reference/command/count/) has edge cases where it may return inaccurate results (see: [Behavior](https://www.mongodb.com/docs/manual/reference/command/count/#behavior)). The `countDocuments()` method implemented in drivers today uses an aggregation pipeline to always return an _exact_ count, and `estimatedDocumentCount()` was introduced to wrap the original command and provide inaccurate counts without the use of a query predicate.

Although it is deprecated, we have no plans to remove [Collection::count()](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-count/) from the PHP library before 2.0. If you'd like to continue to rely on that method, you can likely do so using `raw()` to get the `MongoDB\Collection` object (as @GromNaN suggested above, albeit with `estimatedDocumentCount()`).

> Would it help if we added a new method `Model::estimatedCount()`?

This sounds like a good compromise. IMO, given the choice between correctness and performance we should favor correctness and continue to use `Collection::countDocuments()` in `Model::count()`.

As for the deprecated `MongoDB\Collection::count()` method, directing folks to use [`Query::raw()`](https://github.com/mongodb/laravel-mongodb/blob/v4.0.0-ALPHA2/src/Query/Builder.php#L755) seems preferable than introducing a proxy method in this library.

**Comment by BBrey** [comment]
I would be happy if we could implement the estimateCount() in our code again in the same way we are now using the count(). The solution that has been given isn't working as expected as far as i can see.

**Comment by jmikola** [comment]
> The solution that has been given isn't working as expected as far as i can see.

Did you attempt using `Query::raw()` and calling `count()` on the underlying `MongoDB\Collection` object? That was what I was suggesting in my previous comment:

> As for the deprecated MongoDB\Collection::count() method, directing folks to use [Query::raw()](https://github.com/mongodb/laravel-mongodb/blob/v4.0.0-ALPHA2/src/Query/Builder.php#L755) seems preferable than creating a proxy method for it in this library.

I stand by my statement that it wouldn't make sense to introduce a method for the deprecated `MongoDB\Collection::count()` method in this library, but want to confirm that you're still able to access that method using the existing facilities.
